# Generated by Django 3.2.7 on 2021-09-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='holiday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
