# Generated by Django 3.2.7 on 2021-09-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='holiday',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
